### PR TITLE
modified use of fat arrows to adhere to hapi styleguide

### PR DESCRIPTION
**Pull request by nickux**
Meant to replace #115

### CODE REVIEW

**Comment by jedireza** [comment]
Ok cool. We just need to add the `function` keyword to a few more places in `./setup.js`:

 - line 133 `adminGroup: ['clean', (done) => {`
 - line 137 `admin: ['clean', (done) => {`
 - line 141 `user: ['clean', (done, dbResults) => {`
 - line 145 `adminMembership: ['admin', (done, dbResults) => {`
 - line 158 `linkUser: ['admin', 'user', (done, dbResults) => {`
 - line 172 `linkAdmin: ['admin', 'user', (done, dbResults) => {`

I wish GitHub let me comment about those inline :confused:

**Comment by nickux** [comment]
all set

**Comment by jedireza** [comment]
Thanks! Let's [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) these commits and then I'll merge.

**Comment by nickux** [comment]
done

**Comment by jedireza** [comment]
Thanks!

**Pull request merged**
