### PR TITLE
Refactor User model login test

### PR DESCRIPTION
**Pull request by fourq**
In reference to Issue #41

### CODE REVIEW

**Comment by jedireza** [comment]
Not sure why the build failed maybe it timed out.

We can compress this a bit:
https://github.com/jedireza/frame/compare/fourq:master...jedireza:pr/42

**Comment by fourq** [comment]
That looks much cleaner. Thanks. I see that the build passed now, was it something code related?

**Comment by jedireza** [comment]
Looks like a timeout. Let's see what happens when you commit again after making the changes in the diff.

**Comment by fourq** [comment]
I committed again with suggested changes. I also ran all test. (although I ran all tests the last time too).

**Comment by jedireza** [comment]
That's weird Travis is timing out. I saw this once before.

:+1: Code looks good, I'd like to squash the commits though.

**Comment by fourq** [comment]
Is that something I need to do?

**Comment by jedireza** [comment]
Yes. See: http://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

Since you published to GitHub already you may need to `git push --force` to get your fork updated.

**Comment by jedireza** [comment]
Oh snap. Sorry. I didn't know you squashed (didn't get a notification). Not sure why the build is failing, but I'm merging anyways.

**Pull request merged**
