### PR TITLE
allows the global API_KEY input box to show for Basic or Bearer keys/tokens

### PR DESCRIPTION
**Pull request by bmgdev**

### CODE REVIEW

**Comment by jedireza** [comment]
I originally used basic auth since I expect folks to change it to their liking. Maybe we should go with cookie/session as the default so this is less of an issue?

**Comment by bmgdev** [comment]
I wouldn't change up Basic auth now that you have it.  The global api_key box is usually the best way to work with swagger as you now have the ability for anyone using it to add a basic or bearer token, it was literally a 4 line fix. I've never actually need cookie auth used with Swagger.

Will fix for linter.

**Comment by bmgdev** [comment]
linter issues fixed

**Comment by fishmongr** [comment]
Seconded on the nice fix, thanks @bmgdev! 

I appreciate the thinking behind supporting basic auth but I wouldn't dismiss switching to cookie/session too quickly. For the sake of keeping these comments on topic to the pull request, i'll create a new improvement issue to further discuss that and why I think we should implement it.

**Comment by jedireza** [comment]
Thanks!

**Pull request merged**
