### PR TITLE
Add Swagger

### PR DESCRIPTION
**Pull request by richardzyx**
Following #175 , a PR just for adding Swagger. I would like to keep lout since field description is not shown in hapi-swagger but in lout. I've been using both as documentations for front end developers.

I will open an new issue to discuss some of the other features I would like to add to frame.

Thanks!

### CODE REVIEW

**Comment by jedireza** [comment]
>  I would like to keep lout since field description is not shown in hapi-swagger but in lout.

Hmm. Maybe this would be better as a wiki guide. The changes are pretty straight forward and since we're not replacing `lout` I'm not convinced that this is something we should add by default.

**Comment by richardzyx** [comment]
In that case if we just want to keep one option, I would say Swagger definitely prevail over lout. It's also a key feature offered by rest-hapi so I would just use Swagger as the default implementation.

**Comment by jedireza** [comment]
One of my goals is to keep this project bare bones and with as few dependencies as possible. It's definitely subjective. Some changes (like this one) are probably better left to consumers to customize things to fit their needs.

At this point I suggest we create a guide in the wiki for this. Thanks again for being active and creating these PRs.

**Comment by richardzyx** [comment]
I see. I was aiming for faster setup time for future developers, and I understand where you are coming from.

No problem, happy to help and I hope to see more people adopting frame and aqua. Thanks for the great work!

**Comment by bmgdev** [comment]
+1 on approving this PR.  The addition of Swagger keeps Frame relevant (and still bare bones) with few dependencies.

**Pull request closed without merging**
