### PR TITLE
Update user.name reference in Account and Admin collection

### LINKED ISSUE #179: Update `user.name` reference in `Account`s and `Admin`s collections when a `user.username` is updated
Also see: https://github.com/jedireza/aqua/issues/258

### PR DESCRIPTION
**Pull request by ivanph**
- When the username changes in the Users collection
  the reference in Account and Admin should also be
  updated.

Closes #179

Some coverage is missing, lemme know if you are OK with this approach and I'll add the tests.

### CODE REVIEW

**Comment by jedireza** [comment]
I commented on the Aqua version of this PR. I'm going to close this until we lock down an approach.

Going forward for API changes, I think it best to start the changes in this repo and once we agree on the approach apply the same changes to Aqua. This way you don't have two similar PRs to manage. Once the first one lands the second one will be really quick.

**Comment by jedireza** [comment]
Since we nailed these changes down in https://github.com/jedireza/aqua/pull/264, let's apply those same changes here.

**Comment by jedireza** [comment]
Oh I didn't see that you added a commit. Is this ready to go?

**Comment by ivanph** [comment]
Yeah, I just pushed forced the same changes we did in aqua. Should've
pinged you, sorry about that.

**Pull request merged**
