### PR TITLE
define ModelsPlugin as const to fix eslint errors on npm test run

### PR DESCRIPTION
**Pull request by nickux**
**Fix for linting errors on** `npm test`

```bash
Linting results:
	/Users/njohnson/Projects/frame/test/server/api/admin-groups.js:
		Line 17: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/admins.js:
		Line 17: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/auth-attempts.js:
		Line 17: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/login.js:
		Line 21: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/logout.js:
		Line 18: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/sessions.js:
		Line 17: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/signup.js:
		Line 16: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/statuses.js:
		Line 17: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/api/users.js:
		Line 17: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
	/Users/njohnson/Projects/frame/test/server/auth.js:
		Line 18: prefer-const - 'ModelsPlugin' is never modified, use 'const' instead.
npm ERR! Test failed.  See above for more details.
```

### CODE REVIEW

**Comment by jedireza** [comment]
Very cool thanks! Let's remove the new (empty) file introduced `.eslintignore` and then I'll merge.

**Comment by jedireza** [comment]
:pager: @nickux

**Comment by nickux** [comment]
Didn't see this comment, I must have notifications turned off. Should be all set.

**Comment by jedireza** [comment]
Thanks!

**Pull request merged**
